// lib/screens/main_layout_screen.dart

import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';

// Screens
import 'package:chefbot_app/screens/scanner_screen.dart'; 
import 'package:chefbot_app/screens/infographic_screen.dart';
import 'package:chefbot_app/screens/starred_screen.dart';
import 'package:chefbot_app/screens/profile_screen.dart';
import 'package:chefbot_app/screens/recipe_detail_screen.dart'; 
import 'package:chefbot_app/models/recipes_data.dart'; 
import 'package:chefbot_app/screens/search_screen.dart'; 

class MainLayoutScreen extends StatefulWidget {
  const MainLayoutScreen({super.key});

  @override
  State<MainLayoutScreen> createState() => _MainLayoutScreenState();
}

class _MainLayoutScreenState extends State<MainLayoutScreen> {
  // --- STATE VARIABLES ---
  int _currentIndex = 0; 
  final Color _primaryColor = const Color(0xFFE25324); 
  final supabase = Supabase.instance.client;

  List<String> _availableFilters = ["Under 30m", "Vegetarian", "Healthy"];
  final List<String> _activeFilters = [];
  bool _filtersLoaded = false;

  final TextEditingController _searchController = TextEditingController();
  bool _isSearching = false;
  String _activeSearchQuery = "";
  
  // Search Pagination
  List<dynamic> _searchResults = [];
  bool _isSearchLoading = false;
  int _currentSearchPage = 0;
  bool _hasMoreSearch = true;
  
  // Feed Pagination
  final ScrollController _scrollController = ScrollController();
  List<dynamic> _feedSections = []; 
  int _currentFeedPage = 0; 
  bool _isFeedLoading = false; 
  bool _hasMoreFeed = true; 

  // --- STARRED LOGIC CHANGED TO TITLE TO MATCH DETAIL SCREEN ---
  Set<String> _starredRecipeTitles = {}; 

  @override
  void initState() {
    super.initState();
    _fetchUserFilters();
    _fetchStarredState(); // Updated function name
    
    // Scroll Listener
    _scrollController.addListener(() {
      if (_scrollController.position.pixels >= 
          _scrollController.position.maxScrollExtent - 200) { 
        if (_isSearching) {
           if (!_isSearchLoading && _hasMoreSearch) _fetchNextSearchBatch();
        } else {
           if (!_isFeedLoading && _hasMoreFeed) _fetchNextFeedBatch();
        }
      }
    });
  }

  @override
  void dispose() {
    _searchController.dispose();
    _scrollController.dispose();
    super.dispose();
  }

  // --- STARRED LOGIC (UPDATED TO MATCH RECIPE DETAIL SCREEN) ---

  Future<void> _fetchStarredState() async {
    final userId = supabase.auth.currentUser?.id;
    if (userId == null) return;

    try {
      // Fetch Titles instead of IDs
      final response = await supabase
          .from('saved_recipes')
          .select('title')
          .eq('user_id', userId);
      
      if (mounted) {
        setState(() {
          _starredRecipeTitles = (response as List)
              .map((e) => e['title'] as String)
              .toSet();
        });
      }
    } catch (e) {
      debugPrint("Error fetching starred titles: $e");
    }
  }

  Future<void> _toggleStar(dynamic recipeData) async {
    final userId = supabase.auth.currentUser?.id;
    if (userId == null) return;

    final String title = recipeData['title'] ?? "";
    if (title.isEmpty) return;

    final bool isCurrentlyStarred = _starredRecipeTitles.contains(title);

    // 1. Optimistic UI Update
    setState(() {
      if (isCurrentlyStarred) {
        _starredRecipeTitles.remove(title);
      } else {
        _starredRecipeTitles.add(title);
      }
    });

    try {
      if (isCurrentlyStarred) {
        // UN-STAR: Delete by Title (Matches Detail Screen Logic)
        await supabase
            .from('saved_recipes')
            .delete()
            .eq('user_id', userId)
            .eq('title', title);
            
        if(mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text("Removed from Starred"), duration: Duration(milliseconds: 500)));
      } else {
        // STAR: Insert (Matches Detail Screen Data Structure)
        // We map the incoming JSON data to the DB columns
        final Map<String, dynamic> insertData = {
          'user_id': userId,
          'title': title,
          'image_url': recipeData['image_url'],
          'image_keyword': title, // Backup keyword
          'ingredients': recipeData['ingredients'] ?? [],
          'steps': recipeData['steps'] ?? [],
          'ready_in': recipeData['ready_in'], 
          // 'created_at' is usually auto-generated by DB, but can be sent if needed
        };

        await supabase.from('saved_recipes').insert(insertData);
        
        if(mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text("Saved to Starred!"), duration: Duration(milliseconds: 500)));
      }
    } catch (e) {
      // Revert UI on error
      setState(() {
        if (isCurrentlyStarred) _starredRecipeTitles.add(title);
        else _starredRecipeTitles.remove(title);
      });
      debugPrint("Toggle Star Error: $e");
      if(mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text("Error saving: $e")));
    }
  }

  // --- FILTERS & FEED LOGIC ---

  Future<void> _fetchUserFilters() async {
    final userId = supabase.auth.currentUser?.id;
    if (userId == null) { _fetchNextFeedBatch(); return; }
    try {
      final response = await supabase.from('user_profiles').select('preferences').eq('id', userId).maybeSingle();
      if (response != null && response['preferences'] != null) {
        _updateLocalFiltersFromDB(response['preferences']);
      }
    } catch (e) {
      debugPrint("Error fetching filters: $e");
    } finally {
      _fetchNextFeedBatch();
    }
  }

  void _updateLocalFiltersFromDB(Map<String, dynamic> prefs) {
    if (!mounted) return;
    List<dynamic> dishTypes = prefs['dishTypes'] ?? [];
    List<dynamic> special = prefs['specialPreferences'] ?? [];

    setState(() {
      final Set<String> uniqueFilters = {};
      uniqueFilters.addAll(dishTypes.map((e) => e.toString()));
      uniqueFilters.addAll(special.map((e) => e.toString()));
      uniqueFilters.addAll(["Under 30m", "High Protein", "Low Carb"]);
      _availableFilters = uniqueFilters.toList();
      _filtersLoaded = true;
    });
  }

  Future<void> _checkForPreferenceUpdates() async {
    final userId = supabase.auth.currentUser?.id;
    if (userId == null) return;
    final response = await supabase.from('user_profiles').select('preferences').eq('id', userId).maybeSingle();
    if (response != null && response['preferences'] != null) {
      final prefs = response['preferences'];
      List<dynamic> dishTypes = prefs['dishTypes'] ?? [];
      List<dynamic> special = prefs['specialPreferences'] ?? [];
      final Set<String> newFiltersSet = {};
      newFiltersSet.addAll(dishTypes.map((e) => e.toString()));
      newFiltersSet.addAll(special.map((e) => e.toString()));
      newFiltersSet.addAll(["Under 30m", "High Protein", "Low Carb"]);

      final List<String> newFiltersList = newFiltersSet.toList();
      newFiltersList.sort();
      final currentFiltersList = List<String>.from(_availableFilters)..sort();

      if (newFiltersList.toString() != currentFiltersList.toString()) {
        if (mounted) {
          setState(() {
            _availableFilters = newFiltersSet.toList();
            _activeFilters.removeWhere((f) => !newFiltersSet.contains(f));
            _feedSections.clear();
            _currentFeedPage = 0;
            _hasMoreFeed = true;
          });
          _fetchNextFeedBatch();
        }
      }
    }
  }

  Future<void> _fetchNextFeedBatch() async {
    if (_isFeedLoading) return;
    setState(() => _isFeedLoading = true);
    try {
      final response = await supabase.functions.invoke('home_feed', body: {
        'page': _currentFeedPage, 'filters': _activeFilters,
      });
      final data = response.data;
      if (data == null || data['end'] == true) {
        if (mounted) setState(() { _hasMoreFeed = false; _isFeedLoading = false; });
        return;
      }
      if (mounted) {
        setState(() {
          if (data['new_sections'] != null) {
            _feedSections.addAll(data['new_sections']);
          } else if (data['recipes'] != null) {
             _feedSections.add(data);
          }
          _currentFeedPage++; 
          _isFeedLoading = false;
        });
      }
    } catch (e) {
      if (mounted) setState(() => _isFeedLoading = false);
    }
  }

  // --- SEARCH LOGIC ---
  
  void _performSearch() {
    // Navigate to Search Screen instead of inline
    Navigator.push(context, MaterialPageRoute(builder: (context) => const SearchScreen()));
  }

  // Legacy fetch for inline search (kept if needed, but UI uses SearchScreen now)
  Future<void> _fetchNextSearchBatch() async {
    if (_isSearchLoading) return;
    setState(() => _isSearchLoading = true);

    try {
      final response = await supabase.functions.invoke('home_feed', body: {
        'query': _activeSearchQuery, 
        'filters': _activeFilters,
        'page': _currentSearchPage 
      });

      final data = response.data;
      final List<dynamic> newResults = data['results'] ?? [];

      if (mounted) {
        setState(() {
          if (newResults.isEmpty) {
            _hasMoreSearch = false;
          } else {
            _searchResults.addAll(newResults);
            _currentSearchPage++;
          }
          _isSearchLoading = false;
        });
      }
    } catch (e) {
      debugPrint("Search error: $e");
      if (mounted) setState(() => _isSearchLoading = false);
    }
  }

  void _clearSearch() {
    setState(() { 
      _isSearching = false; 
      _searchController.clear(); 
      _activeSearchQuery = ""; 
      _searchResults = []; 
      _currentSearchPage = 0;
    });
  }

  void _toggleFilter(String filter) {
    setState(() {
      if (_activeFilters.contains(filter)) _activeFilters.remove(filter);
      else _activeFilters.add(filter);
      
      // Reset feed
      _feedSections.clear(); 
      _currentFeedPage = 0; 
      _hasMoreFeed = true; 
      _fetchNextFeedBatch(); 
    });
  }

  // --- UI BUILDERS ---

  Widget _buildHomeBody() {
    return Column(
      children: [
        Container(
          padding: const EdgeInsets.all(16.0),
          color: Colors.white,
          child: Column(
            children: [
              // --- SEARCH BAR (Navigates to SearchScreen) ---
              GestureDetector(
                onTap: () {
                  Navigator.push(
                    context, 
                    MaterialPageRoute(builder: (context) => const SearchScreen())
                  ).then((_) {
                    // Update stars when returning from search/detail screens
                    _fetchStarredState();
                    setState(() {});
                  });
                },
                child: Container(
                  height: 50,
                  decoration: BoxDecoration(
                    color: Colors.grey.shade50,
                    borderRadius: BorderRadius.circular(15),
                    border: Border.all(color: Colors.grey.shade200),
                  ),
                  padding: const EdgeInsets.symmetric(horizontal: 16),
                  child: Row(
                    children: [
                      const Icon(Icons.search, color: Colors.grey),
                      const SizedBox(width: 12),
                      Text(
                        "Search recipes...",
                        style: TextStyle(color: Colors.grey.shade400, fontSize: 16),
                      ),
                    ],
                  ),
                ),
              ),
              const SizedBox(height: 12),
              _buildFilterOptions(),
            ],
          ),
        ),
        Expanded(child: _buildInfiniteFeed()),
      ],
    );
  }

  Widget _buildFilterOptions() {
    return SingleChildScrollView(
      scrollDirection: Axis.horizontal,
      child: Row(
        children: _availableFilters.map((filter) {
          final isSelected = _activeFilters.contains(filter);
          return Padding(
            padding: const EdgeInsets.only(right: 8.0),
            child: FilterChip(
              label: Text(filter),
              selected: isSelected,
              onSelected: (_) => _toggleFilter(filter),
              backgroundColor: Colors.white,
              selectedColor: _primaryColor.withOpacity(0.1),
              labelStyle: TextStyle(
                color: isSelected ? _primaryColor : Colors.grey.shade700,
                fontWeight: isSelected ? FontWeight.bold : FontWeight.w500,
              ),
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20), side: BorderSide(color: isSelected ? _primaryColor : Colors.grey.shade300)),
              showCheckmark: false,
            ),
          );
        }).toList(),
      ),
    );
  }

  Widget _buildInfiniteFeed() {
    if (_feedSections.isEmpty && _isFeedLoading) return Center(child: SpinKitFoldingCube(color: _primaryColor, size: 40));
    
    return RefreshIndicator(
      color: _primaryColor,
      onRefresh: () async { setState(() { _feedSections.clear(); _currentFeedPage = 0; _hasMoreFeed = true; }); _fetchUserFilters(); },
      child: ListView.builder(
        controller: _scrollController, 
        itemCount: _feedSections.length + 1, 
        padding: const EdgeInsets.only(bottom: 20),
        itemBuilder: (context, index) {
          if (index == _feedSections.length) {
            return Padding(padding: const EdgeInsets.all(30.0), child: Center(child: _hasMoreFeed ? SpinKitThreeBounce(color: _primaryColor, size: 20) : const Text("You've reached the end! 🍳", style: TextStyle(color: Colors.grey))));
          }
          return _buildFeedSection(_feedSections[index]);
        },
      ),
    );
  }

  Widget _buildFeedSection(dynamic sectionData) {
    final title = sectionData['section_title'] ?? 'Recommendations';
    final recipes = sectionData['recipes'] as List<dynamic>;
    if (recipes.isEmpty) return const SizedBox.shrink();
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Padding(padding: const EdgeInsets.fromLTRB(16, 24, 16, 12), child: Text(title, style: const TextStyle(fontSize: 20, fontWeight: FontWeight.bold))),
        SizedBox(
          height: 260, 
          child: ListView.builder(
            scrollDirection: Axis.horizontal,
            padding: const EdgeInsets.symmetric(horizontal: 10),
            itemCount: recipes.length,
            itemBuilder: (ctx, i) => _buildHomeRecipeCard(recipes[i]),
          ),
        ),
      ],
    );
  }

  // --- UPDATED CARD STYLE & STAR LOGIC ---
  Widget _buildHomeRecipeCard(dynamic data) {
    // Check starred status using TITLE (Matches Detail Screen)
    final String title = data['title'] ?? "";
    final bool isStarred = _starredRecipeTitles.contains(title);

    return Container(
      width: 180, 
      margin: const EdgeInsets.symmetric(horizontal: 6),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // --- IMAGE & OVERLAYS ---
          Stack(
            children: [
              // 1. Image
              ClipRRect(
                borderRadius: BorderRadius.circular(16),
                child: SizedBox(
                  height: 180, 
                  width: double.infinity,
                  child: Material(
                    color: Colors.transparent,
                    child: InkWell(
                      onTap: () => _navigateToDetail(data, data['image_url'] ?? ""),
                      child: data['image_url'] != null
                          ? Image.network(
                              data['image_url'],
                              fit: BoxFit.cover,
                              errorBuilder: (ctx, err, stack) => Container(
                                  color: Colors.grey[200],
                                  child: const Icon(Icons.broken_image, color: Colors.grey)),
                            )
                          : Container(
                              color: Colors.orange[50],
                              child: const Center(
                                  child: Icon(Icons.restaurant, color: Colors.orange))),
                    ),
                  ),
                ),
              ),

              // 2. Star Button (Top Right)
              Positioned(
                top: 8,
                right: 8,
                child: Material(
                  color: Colors.black.withOpacity(0.3),
                  shape: const CircleBorder(),
                  clipBehavior: Clip.antiAlias,
                  child: InkWell(
                    onTap: () => _toggleStar(data),
                    child: Padding(
                      padding: const EdgeInsets.all(6.0),
                      child: Icon(
                        isStarred ? Icons.star : Icons.star_border,
                        color: Colors.white, // Always white (Filled vs Outline)
                        size: 22,
                      ),
                    ),
                  ),
                ),
              ),

              // 3. Time Badge (Bottom Left)
              Positioned(
                bottom: 8,
                left: 8,
                child: Container(
                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                  decoration: BoxDecoration(
                    color: Colors.black.withOpacity(0.6),
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Text(
                    data['ready_in'] ?? '25 min',
                    style: const TextStyle(
                      color: Colors.white,
                      fontSize: 12,
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
            ],
          ),

          const SizedBox(height: 10),

          // --- TITLE TEXT ---
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 4.0),
            child: Text(
              data['title'] ?? 'Untitled Recipe',
              maxLines: 2,
              overflow: TextOverflow.ellipsis,
              style: TextStyle(
                fontWeight: FontWeight.w600, 
                fontSize: 16,
                color: Colors.grey.shade800,
                height: 1.2
              ),
            ),
          ),
        ],
      ),
    );
  }

  // Note: _buildSearchResults removed as search is handled in SearchScreen now

  void _navigateToDetail(dynamic data, String imageUrl) {
    final recipe = Recipe(
        title: data['title'], 
        imageUrl: imageUrl, 
        ingredients: List<String>.from(data['ingredients'] ?? []), 
        missingIngredients: [], 
        steps: List<String>.from(data['steps'] ?? [])
    );
    Navigator.push(context, MaterialPageRoute(builder: (_) => RecipeDetailScreen(recipe: recipe))).then((_) {
      // Refresh stars when coming back from detail screen
      _fetchStarredState();
      setState(() {});
    });
  }

  Widget _buildNavBarItem(IconData icon, String label, int index) {
    final isSelected = _currentIndex == index;
    return Expanded(
      child: GestureDetector(
        onTap: () {
          setState(() => _currentIndex = index);
          if (index == 0) _checkForPreferenceUpdates();
        },
        behavior: HitTestBehavior.opaque,
        child: Column(
          mainAxisSize: MainAxisSize.min,
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(icon, color: isSelected ? _primaryColor : Colors.grey.shade400, size: isSelected ? 28 : 26),
            const SizedBox(height: 4),
            Text(label, style: TextStyle(fontSize: 12, fontWeight: isSelected ? FontWeight.w600 : FontWeight.w500, color: isSelected ? _primaryColor : Colors.grey.shade400))
          ],
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    Widget currentScreen;
    switch (_currentIndex) {
      case 0: currentScreen = _buildHomeBody(); break;
      case 1: currentScreen = const InfographicScreen(); break;
      case 2: currentScreen = const ScannerScreen(); break;
      case 3: currentScreen = const StarredScreen(); break;
      case 4: currentScreen = const ProfileScreen(); break;
      default: currentScreen = _buildHomeBody();
    }
    
    return Scaffold(
       backgroundColor: Colors.white,
       appBar: _currentIndex == 0 ? AppBar(
        title: Row(children: [Text("ChefBot", style: TextStyle(fontWeight: FontWeight.bold, color: _primaryColor, fontSize: 22)), const SizedBox(width: 5), Icon(Icons.auto_awesome, color: _primaryColor, size: 20)]),
        backgroundColor: Colors.white, elevation: 0,
      ) : null,
      
      body: currentScreen,

      floatingActionButton: SizedBox(
        height: 60, width: 60,
        child: FloatingActionButton(
          onPressed: () => setState(() => _currentIndex = 2),
          backgroundColor: _primaryColor,
          elevation: 3,
          shape: const CircleBorder(),
          child: const Icon(Icons.camera_alt, color: Colors.white, size: 28),
        ),
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,

      bottomNavigationBar: BottomAppBar(
        shape: const CircularNotchedRectangle(),
        notchMargin: 0.0, 
        color: Colors.white,
        surfaceTintColor: Colors.white,
        shadowColor: Colors.black12,
        elevation: 10,
        padding: EdgeInsets.zero,
        child: SizedBox(
          height: 65,
          child: Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              _buildNavBarItem(Icons.home_rounded, 'Home', 0),
              _buildNavBarItem(Icons.menu, 'Infographic', 1),
              Expanded(
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.end,
                  children: [
                    const SizedBox(height: 32), 
                    Text(
                      "Scan",
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 12,
                        fontWeight: _currentIndex == 2 ? FontWeight.w600 : FontWeight.w500,
                        color: _currentIndex == 2 ? _primaryColor : Colors.grey.shade400,
                      ),
                    ),
                    const SizedBox(height: 8), 
                  ],
                ),
              ),
              _buildNavBarItem(Icons.star, 'Starred', 3),
              _buildNavBarItem(Icons.person_rounded, 'Profile', 4),
            ],
          ),
        ),
      ),
    );
  }
}